const { PrismaClient } = require('@prisma/client');
const fs = require('fs');

const prisma = new PrismaClient();

async function main() {
  // Read the SQL file generated by PowerShell (which uses UTF-16LE encoding by default)
  const sqlContent = fs.readFileSync('create_tables.sql', 'utf16le');
  
  // Split the file into individual statements to avoid multi-statement issues with Prisma
  const statements = sqlContent.split(';').map(s => s.trim()).filter(s => s.length > 0);
  
  for (const statement of statements) {
    console.log(`Executing: ${statement.substring(0, 50)}...`);
    try {
      await prisma.$executeRawUnsafe(statement);
    } catch (e) {
      if (e.message.includes('already exists')) {
        console.log('Skipped (already exists)');
      } else {
        throw e;
      }
    }
  }
  
  console.log('All tables created successfully!');
}

main().catch(e => {
  console.error('Error during execution:', e);
  process.exit(1);
}).finally(() => {
  prisma.$disconnect();
});
